repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^gcp-services/gcs-file-ingest-service/.*\.py$
      - id: ruff-format
        files: ^gcp-services/gcs-file-ingest-service/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^gcp-services/gcs-file-ingest-service/.*\.py$
        args: [--ignore-missing-imports, --no-strict-optional]
